version: '3'

services:
  postgres:
    build:
      context: ./database
    environment:
      POSTGRES_PASSWORD: "Countdown10"
    ports:
      - "5432:5432"
    networks:
      - todonetwork

  backend:
    build:
      context: ./backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=postgres
      - DB_CONNECTION_STRING=postgres://postgres:Countdown10@postgres:5432/movies
    ports:
      - "7280:7280"
    networks:
      - todonetwork
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - todonetwork
    depends_on:
      - backend

networks:
  todonetwork:
    driver: bridge
